"""Shared utilities for all auto-hinting engines (e.g., local and remote)."""

# truncation limits for diagnostic output and file content
HINT_DIAG_TRUNCATE = 2000
HINT_FILE_LINES = 20

# keys for custom validation rules in the quality JSON file
MUST_CONTAIN_KEY = "must_contain"
CANNOT_CONTAIN_KEY = "cannot_contain"

# message role constants
ROLE_SYSTEM = "system"
ROLE_USER = "user"

# user message parts
CHECK_LABEL = "Check"
COMMAND_LABEL = "Command"
CODE_LABEL = "Code"
DIAGNOSTIC_LABEL = "Diagnostic"
DETAILS_LABEL = "Details"

# formatting constants
CODE_BLOCK_OPEN = "Code:\n```\n"
CODE_BLOCK_CLOSE = "\n```"
DIAG_BLOCK_OPEN = "Diagnostic:\n```\n"
DIAG_BLOCK_CLOSE = "\n```"
USER_SEPARATOR = "\n\n"

# default system prompt constants
SYS_INTRO = "You give short, direct hints for fixing code. "
SYS_CRITICAL_HEADER = "CRITICAL RULES:\n"
SYS_TEST_CORRECT = (
    "- The test suite is provided by the instructor and is ALWAYS correct.\n"
)
SYS_ALWAYS_MENTION = "- ALWAYS mention what test or command failed.\n"
SYS_ALWAYS_DESCRIBE = (
    "- ALWAYS describe what to change in the student's implementation.\n"
)
SYS_ALWAYS_EXPLAIN = (
    "- ALWAYS explain what is incorrect in the STUDENT's source code.\n"
)
SYS_ALWAYS_SUGGEST = "- ALWAYS suggest running the command that produced the diagnostic output to verify the fix.\n\n"
SYS_ALWAYS_END_PERIOD = "- ALWAYS end every hint with a period.\n\n"
SYS_NEVER_QUOTES = "- NEVER use single quotes (for example, ') or backticks (for example, `) in your response.\n"
SYS_NEVER_MODIFY = (
    "- NEVER suggest modifying tests, test assertions, or expected results.\n"
)
SYS_NEVER_FENCE = "- NEVER write fenced source code blocks in your hint.\n"
SYS_NEVER_WORDS = "- NEVER use the words 'student', 'you should', or 'you might'. NEVER say:\n"
SYS_NEVER_SAY_1 = "- 'The test incorrectly asserts <...>'\n"
SYS_NEVER_SAY_2 = "- 'Modify the test to <...>'\n"
SYS_NEVER_SAY_3 = "- 'The assertion is wrong because <...>'\n"
SYS_NEVER_SAY_4 = "- 'Change the expected result <...>'\n\n"
SYS_INSTEAD_HEADER = "INSTEAD say:\n"
SYS_INSTEAD_1 = (
    "- 'The function X returns Y but the test expects Z; check...'\n"
)
SYS_INSTEAD_2 = (
    "- 'The implementation does not handle...; add logic to...'\n\n"
)

# user message suffix asking the LLM what to do
USER_QUESTION = (
    "What to do: Write 3-5 sentences, mentioning the specific "
    "failing test/command/check if available."
)

# built-in validation phrases for the cannot_contain check
PHRASE_TEST_INCORRECTLY = "test incorrectly"
PHRASE_TEST_IS_WRONG = "test is wrong"
PHRASE_TEST_SHOULD_BE = "test should be"
PHRASE_MODIFY_TEST = "modify the test"
PHRASE_CHANGE_TEST = "change the test"
PHRASE_FIX_TEST = "fix the test"
PHRASE_UPDATE_TEST = "update the test"
PHRASE_ASSERTION_WRONG = "the assertion is wrong"
PHRASE_ASSERTION_INCORRECTLY = "the assertion incorrectly"
PHRASE_INCORRECTLY_ASSERTS = "incorrectly asserts"
PHRASE_WRONG_ASSERTION = "wrong assertion"
PHRASE_CHANGE_ASSERTION = "change the assertion"
PHRASE_MODIFY_ASSERTION = "modify the assertion"
PHRASE_CHANGE_ASSERT = "change the assert"
PHRASE_UPDATE_ASSERT = "update the assert"
PHRASE_FIX_ASSERTION = "fix the assertion"
PHRASE_CHANGE_EXPECTED = "change the expected"
PHRASE_MODIFY_EXPECTED = "modify the expected"
PHRASE_WE_NEED = "we need"
PHRASE_WE_SHOULD = "we should"
PHRASE_WRONG_EXPECTED = "wrong expected"
PHRASE_EXPECTED_WRONG = "expected result is wrong"
PHRASE_EXPECTED_VALUE_WRONG = "expected value is wrong"


def build_hint_messages(  # noqa: PLR0913
    description: str,
    diagnostic: str = "",
    command: str = "",
    file_content: str = "",
    system_prompt: str | None = None,
    details: str = "",
) -> list[dict[str, str]]:
    """Build a structured message list for hint generation.

    Produces the same system prompt and user message regardless of
    whether the hint will be generated by a local transformers
    pipeline or a remote OpenAI-compatible API.

    When a custom system_prompt is provided (e.g. from a
    system_prompt_file in the config front matter), it replaces
    the default built-in system prompt entirely.

    Args:
        description: Check description.
        diagnostic: Diagnostic output (truncated internally).
        command: Command that was run.
        file_content: Source file content (truncated to
            HINT_FILE_LINES lines).
        system_prompt: Optional custom system prompt to use
            instead of the built-in default.
        details: Structured details about the check
            configuration (e.g. options and expected values).

    Returns:
        A list of dicts with role and content keys,
        suitable for chat-based inference.

    """
    truncated_diag = diagnostic[:HINT_DIAG_TRUNCATE] if diagnostic else ""
    truncated_file = ""
    if file_content:
        lines = file_content.split("\n")
        truncated_file = "\n".join(lines[:HINT_FILE_LINES])
    system = (
        system_prompt
        if system_prompt
        else (
            SYS_INTRO
            + SYS_CRITICAL_HEADER
            + SYS_TEST_CORRECT
            + SYS_ALWAYS_MENTION
            + SYS_ALWAYS_DESCRIBE
            + SYS_ALWAYS_EXPLAIN
            + SYS_ALWAYS_SUGGEST
            + SYS_ALWAYS_END_PERIOD
            + SYS_NEVER_QUOTES
            + SYS_NEVER_MODIFY
            + SYS_NEVER_FENCE
            + SYS_NEVER_WORDS
            + SYS_NEVER_SAY_1
            + SYS_NEVER_SAY_2
            + SYS_NEVER_SAY_3
            + SYS_NEVER_SAY_4
            + SYS_INSTEAD_HEADER
            + SYS_INSTEAD_1
            + SYS_INSTEAD_2
        )
    )
    user_parts = [f"{CHECK_LABEL}: {description}"]
    if command:
        user_parts.append(f"{COMMAND_LABEL}: {command}")
    if truncated_file:
        user_parts.append(CODE_BLOCK_OPEN + truncated_file + CODE_BLOCK_CLOSE)
    if truncated_diag:
        user_parts.append(DIAG_BLOCK_OPEN + truncated_diag + DIAG_BLOCK_CLOSE)
    if details:
        user_parts.append(f"{DETAILS_LABEL}: {details}")
    user_parts.append(USER_QUESTION)

    return [
        {"role": ROLE_SYSTEM, "content": system},
        {"role": ROLE_USER, "content": USER_SEPARATOR.join(user_parts)},
    ]


def is_valid_hint(
    hint: str,
    custom_rules: dict[str, list[str]] | None = None,
) -> bool:
    """Check if a generated hint passes the quality rules.

    Quality is determined by two categories of phrase checks:

    - must_contain: phrases that must appear in the hint
      (case-insensitive substring match). Every phrase must be
      present for the hint to be valid.
    - cannot_contain: phrases that must NOT appear in the
      hint (case-insensitive substring match). If any phrase is
      found, the hint is invalid.

    Built-in defaults exist for both categories. When custom
    rules are provided via a JSON file, they **completely
    replace** the built-in defaults (matching the override
    behaviour of system_prompt_file).

    Args:
        hint: The generated hint text.
        custom_rules: Optional dict with must_contain and/or
            cannot_contain lists of phrases. When provided,
            these replace the built-in rules entirely. Each
            phrase is matched case-insensitively as a substring.

    Returns:
        True if the hint passes all quality checks, False if it
        fails any check.

    """
    hint_lower = hint.lower()
    # by default, there is nothing specified for the must contain
    # checking list, but there is the option for the person using
    # gatorgrade to specify a list of phrases that must be specified
    must_contain: list[str] = []
    # these are the default phrases that should not be inside of the
    # automatically generated hints; if one of these phrases is found
    # then this means that the hint will be highlighted as invalid
    cannot_contain = [
        PHRASE_TEST_INCORRECTLY,
        PHRASE_TEST_IS_WRONG,
        PHRASE_TEST_SHOULD_BE,
        PHRASE_MODIFY_TEST,
        PHRASE_CHANGE_TEST,
        PHRASE_FIX_TEST,
        PHRASE_UPDATE_TEST,
        PHRASE_ASSERTION_WRONG,
        PHRASE_ASSERTION_INCORRECTLY,
        PHRASE_INCORRECTLY_ASSERTS,
        PHRASE_WRONG_ASSERTION,
        PHRASE_CHANGE_ASSERTION,
        PHRASE_MODIFY_ASSERTION,
        PHRASE_CHANGE_ASSERT,
        PHRASE_UPDATE_ASSERT,
        PHRASE_FIX_ASSERTION,
        PHRASE_CHANGE_EXPECTED,
        PHRASE_MODIFY_EXPECTED,
        PHRASE_WE_NEED,
        PHRASE_WE_SHOULD,
        PHRASE_WRONG_EXPECTED,
        PHRASE_EXPECTED_WRONG,
        PHRASE_EXPECTED_VALUE_WRONG,
    ]
    # custom rules completely replace built-in defaults
    if custom_rules is not None:
        # there is a must contain rule replacement
        if MUST_CONTAIN_KEY in custom_rules:
            must_contain = custom_rules[MUST_CONTAIN_KEY]
        # there is a cannot contain rule replacement
        if CANNOT_CONTAIN_KEY in custom_rules:
            cannot_contain = custom_rules[CANNOT_CONTAIN_KEY]
    # all must-contain phrases must be present
    for phrase in must_contain:
        if phrase.lower() not in hint_lower:
            return False
    # no cannot-contain phrase may be present
    for phrase in cannot_contain:
        if phrase.lower() in hint_lower:
            return False
    return True
